### ISSUE TITLE
KeyCloak better than Ory Hydra?

### ISSUE THREAD

**Issue by jdsika** [GAIA-X4PLC-AAD/ssi-to-oidc-bridge#33]
I hear from many sides that they all use https://www.keycloak.org/

Did you compare solutions? Should we switch?

**Comment by jfelixh** [comment]
Transferred issue to correct repo.

**Comment by jfelixh** [comment]
Keycloak (among other things) aggregates IAM protocols like OIDC and SAML. Since we support OIDC with Ory Hydra as the specific implementation, we are fully compatible with Keycloak. This was a consideration from the start. We do not use Keycloak directly to keep complexity down. For many scenarios, it is just overkill. Ory Hydra was chosen because it makes modifications to the internal authentication logic particularly easy.

That means that in addition to being standalone, the bridge can also be integrated into a Keycloak. That could make sense to connect to a system that only knows SAML 2.0 and not OIDC. Or it could make sense for a big organization that bundles all their IAM in their Keycloak instance.
